name: Deploy To Edgio (production)

on: workflow_dispatch

jobs:
  deploy-to-edgio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm run edgio:deploy --token=$EDGIO_DEPLOY_TOKEN
        env:
          EDGIO_DEPLOY_TOKEN: ${{secrets.EDGIO_DEPLOY_TOKEN}}
