on:
  issues:
    types: [opened, edited, deleted]

jobs:
  issue_commented:
    name: Issue Comment GH Action
    runs-on: ubuntu-latest
    steps:
      - run: node update-map.js
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
