on:
  issues:
    types: [opened, edited, deleted]

jobs:
  issue_commented:
    name: Issue Comment GH Action
    runs-on: ubuntu-latest
    steps:
      - run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
